name: CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
    - name: Setup project
      run: |
        pip install -e .[ci]
    - name: Lint
      run: |
        black --diff src/ottd_prayer
        isort --check-only src/ottd_prayer
    - name: Type check
      run: |
        stubgen -p dacite -p openttd_protocol
        mypy
